title: My Portfolio
description: Personal portfolio website for SITE 1101
theme: null

# If your GitHub Pages URL is like:
# https://omaralifzade.github.io/website3/
# then set baseurl to "/website3"
baseurl: "/website3"

# If your site is hosted at:
# https://username.github.io/
# then set baseurl to ""
# baseurl: ""

url: ""
